"""Hyperliquid autonomous trading agent with strategy execution and risk management.

This agent can:
- Develop and execute autonomous trading strategies
- Execute human-provided trading strategies
- Analyze markets using advanced LLM reasoning
- Manage risk with comprehensive safety controls
- Track performance and maintain trade history
"""

from __future__ import annotations

import asyncio
import os
from datetime import datetime
from typing import Any, Literal, Optional
from mirascope import llm
from pydantic import BaseModel, Field

from .strategies import (
    StrategyType,
    TradingStrategy,
    TradingSignal,
    SignalStrength,
    get_strategy_by_type,
)
from .risk_manager import RiskManager, RiskParams, RiskCheckResult, PortfolioRisk
from .state_manager import StateManager, PerformanceSnapshot, TradeRecord

# Import Hyperliquid tools
try:
    from ...tools.hyperliquid_trading.tool import (
        check_account_balance,
        get_open_positions,
        get_market_data,
        place_market_order,
        place_limit_order,
        close_position,
        get_funding_rate,
        get_order_book,
    )

    HYPERLIQUID_TOOLS_AVAILABLE = True
except ImportError:
    HYPERLIQUID_TOOLS_AVAILABLE = False
    check_account_balance = None
    get_open_positions = None
    get_market_data = None
    place_market_order = None
    place_limit_order = None
    close_position = None
    get_funding_rate = None
    get_order_book = None


# Response models
class MarketAnalysis(BaseModel):
    """Market analysis result."""

    coin: str = Field(..., description="Trading pair analyzed")
    trend: Literal["bullish", "bearish", "neutral"] = Field(..., description="Current trend")
    trend_strength: SignalStrength = Field(..., description="Trend strength")
    key_levels: dict[str, float] = Field(..., description="Key support/resistance levels")
    sentiment: str = Field(..., description="Market sentiment analysis")
    indicators: dict[str, Any] = Field(..., description="Technical indicator values")
    recommendation: str = Field(..., description="Trading recommendation")
    confidence: float = Field(..., description="Analysis confidence 0-1")
    reasoning: str = Field(..., description="Detailed reasoning for analysis")


class AutonomousStrategyPlan(BaseModel):
    """Autonomous strategy plan generated by the agent."""

    strategy_name: str = Field(..., description="Strategy name")
    strategy_type: StrategyType = Field(..., description="Strategy type")
    description: str = Field(..., description="Strategy description")
    markets: list[str] = Field(..., description="Markets to trade")
    entry_criteria: str = Field(..., description="Entry criteria")
    exit_criteria: str = Field(..., description="Exit criteria")
    risk_management: str = Field(..., description="Risk management approach")
    expected_performance: str = Field(..., description="Expected performance characteristics")
    reasoning: str = Field(..., description="Why this strategy is appropriate")


class TradeDecision(BaseModel):
    """Decision to execute a trade."""

    should_trade: bool = Field(..., description="Whether to execute the trade")
    coin: str = Field(..., description="Trading pair")
    action: Literal["buy", "sell", "hold", "close"] = Field(..., description="Action to take")
    size_usd: Optional[float] = Field(None, description="Trade size in USD")
    entry_type: Literal["market", "limit"] = Field("market", description="Order type")
    limit_price: Optional[float] = Field(None, description="Limit price if limit order")
    stop_loss: Optional[float] = Field(None, description="Stop loss price")
    take_profit: Optional[float] = Field(None, description="Take profit price")
    reasoning: str = Field(..., description="Reasoning for the decision")
    confidence: float = Field(..., description="Confidence in decision 0-1")


# LLM-powered analysis functions
@llm.call(
    provider="openrouter",
    model_id=os.getenv("HYPERLIQUID_MODEL_ID", "anthropic/claude-3.5-sonnet"),
    format=MarketAnalysis,
)
async def analyze_market_conditions(
    coin: str,
    market_data: dict[str, Any],
    order_book: dict[str, Any],
    funding_rate: dict[str, Any],
) -> str:
    """Analyze market conditions for a trading pair using advanced reasoning.

    Args:
        coin: Trading pair to analyze
        market_data: Current market data
        order_book: Order book data
        funding_rate: Funding rate information

    Returns:
        Comprehensive market analysis
    """
    return f"""You are an expert cryptocurrency trader analyzing market conditions for {coin}.

Current Market Data:
- Price: ${market_data.get('mark_price', 0):.2f}
- 24h Volume: ${market_data.get('volume_24h', 0):.2f}
- 24h Change: {market_data.get('price_change_24h', 0):.2f}%
- Open Interest: ${market_data.get('open_interest', 0):.2f}
- Current Funding Rate: {funding_rate.get('current_funding_rate', 0):.4f}%

Order Book Data:
- Best Bid: ${order_book.get('bids', [{}])[0].get('price', 0):.2f} (Size: {order_book.get('bids', [{}])[0].get('size', 0):.4f})
- Best Ask: ${order_book.get('asks', [{}])[0].get('price', 0):.2f} (Size: {order_book.get('asks', [{}])[0].get('size', 0):.4f})
- Bid/Ask Spread: {((order_book.get('asks', [{}])[0].get('price', 0) - order_book.get('bids', [{}])[0].get('price', 0)) / order_book.get('bids', [{}])[0].get('price', 1) * 100):.3f}%

Analyze this market comprehensively:

1. **Trend Analysis**: Determine the current trend (bullish/bearish/neutral) and its strength
2. **Key Levels**: Identify important support and resistance levels
3. **Order Flow**: Analyze order book imbalances and liquidity
4. **Funding Dynamics**: Interpret funding rate implications
5. **Sentiment**: Assess overall market sentiment
6. **Technical Indicators**: Evaluate relevant technical signals

Provide:
- Clear trend direction and strength
- Key price levels (support/resistance)
- Market sentiment assessment
- Technical indicator analysis
- Trading recommendation (buy/sell/hold)
- Confidence level (0-1)
- Detailed reasoning for your analysis

Be objective and data-driven in your analysis."""


@llm.call(
    provider="openrouter",
    model_id=os.getenv("HYPERLIQUID_MODEL_ID", "anthropic/claude-3.5-sonnet"),
    format=AutonomousStrategyPlan,
)
async def develop_autonomous_strategy(
    markets: list[str],
    market_analyses: list[dict[str, Any]],
    capital: float,
    risk_tolerance: str,
    time_horizon: str,
) -> str:
    """Develop an autonomous trading strategy based on market conditions.

    Args:
        markets: Available markets to trade
        market_analyses: Analysis of each market
        capital: Available trading capital
        risk_tolerance: Risk tolerance level
        time_horizon: Trading time horizon

    Returns:
        Complete autonomous strategy plan
    """
    analyses_str = "\n\n".join([f"**{a['coin']}**:\n- Trend: {a['trend']}\n- Sentiment: {a['sentiment']}\n- Recommendation: {a['recommendation']}" for a in market_analyses])

    return f"""You are an expert algorithmic trading strategist developing a trading strategy.

Available Capital: ${capital:.2f}
Risk Tolerance: {risk_tolerance}
Time Horizon: {time_horizon}

Markets Available: {', '.join(markets)}

Market Analyses:
{analyses_str}

Based on current market conditions, develop a comprehensive autonomous trading strategy:

1. **Strategy Selection**: Choose the most appropriate strategy type:
   - Trend Following: For strong directional markets
   - Mean Reversion: For ranging/oscillating markets
   - Funding Arbitrage: For high funding rate opportunities
   - Breakout: For consolidation breakouts
   - Momentum: For strong momentum plays

2. **Market Selection**: Choose which markets to focus on based on:
   - Liquidity and volume
   - Trend clarity
   - Risk/reward potential
   - Correlation considerations

3. **Entry/Exit Rules**: Define clear, objective rules for:
   - When to enter positions
   - When to exit with profit
   - When to cut losses

4. **Risk Management**: Specify:
   - Position sizing approach
   - Stop loss methodology
   - Maximum drawdown tolerance

5. **Expected Performance**: Describe:
   - Anticipated win rate
   - Risk/reward ratio
   - Expected return profile

Provide a complete, actionable strategy that can be executed systematically."""


@llm.call(
    provider="openrouter",
    model_id=os.getenv("HYPERLIQUID_MODEL_ID", "anthropic/claude-3.5-sonnet"),
    format=TradeDecision,
    tools=[place_market_order, place_limit_order, close_position] if HYPERLIQUID_TOOLS_AVAILABLE else [],
)
async def make_trade_decision(
    strategy: dict[str, Any],
    market_analysis: dict[str, Any],
    current_positions: list[dict[str, Any]],
    capital: float,
    risk_check: dict[str, Any],
) -> str:
    """Make a trading decision based on strategy and market analysis.

    Args:
        strategy: Trading strategy configuration
        market_analysis: Current market analysis
        current_positions: Existing open positions
        capital: Available capital
        risk_check: Risk check results

    Returns:
        Trade decision
    """
    positions_str = "\n".join([f"- {p['coin']}: {p['side']} {p['size']} @ ${p['entry_price']}" for p in current_positions]) if current_positions else "No open positions"

    return f"""You are a trading execution specialist making trade decisions based on strategy and analysis.

Strategy: {strategy['name']} ({strategy['type']})
Entry Rules: {strategy.get('entry_rules', 'N/A')}
Exit Rules: {strategy.get('exit_rules', 'N/A')}
Max Positions: {strategy.get('max_positions', 3)}

Market Analysis:
- Coin: {market_analysis['coin']}
- Trend: {market_analysis['trend']} ({market_analysis['trend_strength']})
- Sentiment: {market_analysis['sentiment']}
- Recommendation: {market_analysis['recommendation']}
- Confidence: {market_analysis['confidence']:.2f}

Current Positions:
{positions_str}

Available Capital: ${capital:.2f}

Risk Check Results:
- Approved: {risk_check.get('approved', False)}
- Reason: {risk_check.get('reason', 'N/A')}
- Warnings: {', '.join(risk_check.get('warnings', [])) if risk_check.get('warnings') else 'None'}

Based on the strategy rules, market analysis, and risk constraints, decide:

1. **Should Trade**: Whether to execute a trade now
2. **Action**: buy, sell, hold, or close existing position
3. **Size**: Appropriate position size in USD (if trading)
4. **Order Type**: market or limit order
5. **Risk Management**: Stop loss and take profit levels
6. **Reasoning**: Detailed explanation for the decision
7. **Confidence**: Your confidence level (0-1)

Only recommend trades that:
- Align with the strategy's entry rules
- Pass risk management checks
- Have strong supporting analysis
- Fit within position limits

Be conservative and prioritize capital preservation."""


# Main Trading Agent
class HyperliquidTradingAgent:
    """Autonomous trading agent for Hyperliquid DEX."""

    def __init__(
        self,
        starting_capital: float,
        risk_params: Optional[RiskParams] = None,
        db_path: str = "hyperliquid_trading_state.db",
        testnet: bool = True,
    ):
        """Initialize trading agent.

        Args:
            starting_capital: Starting capital in USD
            risk_params: Risk management parameters
            db_path: Path to state database
            testnet: Use testnet (default: True for safety)
        """
        self.starting_capital = starting_capital
        self.testnet = testnet

        # Initialize managers
        self.risk_params = risk_params or RiskParams()
        self.risk_manager = RiskManager(self.risk_params, starting_capital)
        self.state_manager = StateManager(db_path)

        # Track current capital (will be updated from account balance)
        self.current_capital = starting_capital

    async def get_current_capital(self) -> float:
        """Get current account capital from Hyperliquid.

        Returns:
            Current capital in USD
        """
        if not HYPERLIQUID_TOOLS_AVAILABLE:
            return self.current_capital

        balance = check_account_balance(testnet=self.testnet)
        if "error" not in balance:
            self.current_capital = balance["account_value"]
        return self.current_capital

    async def analyze_market(self, coin: str) -> MarketAnalysis:
        """Analyze a market using comprehensive data and LLM reasoning.

        Args:
            coin: Trading pair to analyze

        Returns:
            Market analysis
        """
        # Gather market data
        market_data = get_market_data(coin, testnet=self.testnet)
        order_book = get_order_book(coin, depth=10, testnet=self.testnet)
        funding_rate = get_funding_rate(coin, testnet=self.testnet)

        # Use LLM to analyze
        analysis = await analyze_market_conditions(
            coin=coin,
            market_data=market_data,
            order_book=order_book,
            funding_rate=funding_rate,
        )

        return analysis

    async def develop_strategy(
        self,
        markets: list[str],
        risk_tolerance: Literal["conservative", "moderate", "aggressive"] = "moderate",
        time_horizon: Literal["short", "medium", "long"] = "medium",
    ) -> TradingStrategy:
        """Develop an autonomous trading strategy.

        Args:
            markets: Markets to consider
            risk_tolerance: Risk tolerance level
            time_horizon: Trading time horizon

        Returns:
            Developed trading strategy
        """
        # Analyze each market
        market_analyses = []
        for coin in markets:
            analysis = await self.analyze_market(coin)
            market_analyses.append(analysis.model_dump())

        # Get current capital
        capital = await self.get_current_capital()

        # Have LLM develop strategy
        strategy_plan = await develop_autonomous_strategy(
            markets=markets,
            market_analyses=market_analyses,
            capital=capital,
            risk_tolerance=risk_tolerance,
            time_horizon=time_horizon,
        )

        # Convert to TradingStrategy
        strategy = TradingStrategy(
            type=strategy_plan.strategy_type,
            name=strategy_plan.strategy_name,
            description=strategy_plan.description,
            markets=strategy_plan.markets,
            entry_rules=strategy_plan.entry_criteria,
            exit_rules=strategy_plan.exit_criteria,
            risk_per_trade=self.risk_params.stop_loss_pct,
            max_positions=self.risk_params.max_positions,
            use_stop_loss=self.risk_params.use_stop_loss,
            use_take_profit=self.risk_params.use_take_profit,
        )

        return strategy

    async def execute_strategy_iteration(
        self,
        strategy: TradingStrategy,
    ) -> dict[str, Any]:
        """Execute one iteration of a trading strategy.

        Args:
            strategy: Trading strategy to execute

        Returns:
            Iteration results including actions taken
        """
        results = {
            "timestamp": datetime.now(),
            "actions": [],
            "analyses": [],
            "errors": [],
        }

        # Get current state
        capital = await self.get_current_capital()
        current_positions = get_open_positions(testnet=self.testnet)

        # Analyze each market in strategy
        for coin in strategy.markets:
            try:
                # Analyze market
                analysis = await self.analyze_market(coin)
                results["analyses"].append(analysis.model_dump())

                # Check if we should trade this market
                # First, check if we already have a position
                existing_position = next((p for p in current_positions if p["coin"] == coin), None)

                if existing_position:
                    # Check if we should close the position
                    if analysis.recommendation.lower() == "sell" and existing_position["side"] == "long":
                        results["actions"].append({"action": "close_position", "coin": coin, "reason": "Exit signal from analysis"})
                        # Close position
                        close_result = close_position(coin, testnet=self.testnet)
                        if close_result.get("success"):
                            self.state_manager.record_trade_exit(
                                coin=coin,
                                exit_price=analysis.key_levels.get("current", 0),
                                exit_reason="Strategy exit signal",
                            )
                    continue  # Skip to next market if we have a position

                # Check if we're at max positions
                if len(current_positions) >= strategy.max_positions:
                    continue

                # Consider new position
                if analysis.recommendation.lower() == "buy" and analysis.confidence > 0.6:
                    # Calculate position size
                    entry_price = analysis.key_levels.get("current", 0)
                    stop_loss = self.risk_manager.calculate_stop_loss(entry_price, "long")
                    position_size = self.risk_manager.calculate_position_size(
                        capital=capital,
                        entry_price=entry_price,
                        stop_loss_price=stop_loss,
                        risk_pct=strategy.risk_per_trade,
                    )

                    size_usd = position_size * entry_price

                    # Risk check
                    risk_check = self.risk_manager.check_new_position(
                        coin=coin,
                        size_usd=size_usd,
                        entry_price=entry_price,
                        stop_loss_price=stop_loss,
                        current_capital=capital,
                        current_positions=len(current_positions),
                    )

                    if risk_check.approved and not risk_check.requires_approval:
                        # Execute trade
                        take_profit = self.risk_manager.calculate_take_profit(entry_price, "long", risk_reward_ratio=2.0)

                        order_result = place_market_order(
                            coin=coin,
                            side="buy",
                            size=position_size,
                            testnet=self.testnet,
                        )

                        if order_result.get("success"):
                            # Record trade
                            self.state_manager.record_trade_entry(
                                coin=coin,
                                side="long",
                                entry_price=entry_price,
                                size=position_size,
                                strategy=strategy.name,
                                entry_reason=analysis.reasoning,
                                stop_loss=stop_loss,
                                take_profit=take_profit,
                            )

                            results["actions"].append(
                                {
                                    "action": "opened_position",
                                    "coin": coin,
                                    "size": position_size,
                                    "entry_price": entry_price,
                                    "stop_loss": stop_loss,
                                    "take_profit": take_profit,
                                }
                            )

            except Exception as e:
                results["errors"].append({"coin": coin, "error": str(e)})

        return results

    async def run_autonomous_trading(
        self,
        markets: list[str],
        duration_hours: int = 24,
        check_interval_minutes: int = 15,
    ) -> dict[str, Any]:
        """Run autonomous trading for a specified duration.

        Args:
            markets: Markets to trade
            duration_hours: How long to run (hours)
            check_interval_minutes: Minutes between strategy checks

        Returns:
            Summary of trading session
        """
        # Develop strategy
        strategy = await self.develop_strategy(markets=markets)

        print(f"🤖 Autonomous Trading Started")
        print(f"Strategy: {strategy.name}")
        print(f"Markets: {', '.join(strategy.markets)}")
        print(f"Duration: {duration_hours}h, Check Interval: {check_interval_minutes}m")
        print(f"Starting Capital: ${self.current_capital:.2f}")

        start_time = datetime.now()
        iterations = 0

        while (datetime.now() - start_time).total_seconds() < duration_hours * 3600:
            iterations += 1
            print(f"\n--- Iteration {iterations} ---")

            # Execute strategy iteration
            results = await self.execute_strategy_iteration(strategy)

            # Log results
            if results["actions"]:
                print(f"Actions taken: {len(results['actions'])}")
                for action in results["actions"]:
                    print(f"  - {action}")

            if results["errors"]:
                print(f"Errors: {len(results['errors'])}")

            # Save performance snapshot
            capital = await self.get_current_capital()
            metrics = self.state_manager.calculate_performance_metrics()

            snapshot = PerformanceSnapshot(
                timestamp=datetime.now(),
                capital=capital,
                total_pnl=capital - self.starting_capital,
                daily_pnl=0,  # Would need to track this properly
                open_positions=len(get_open_positions(testnet=self.testnet)),
                total_trades=metrics["total_trades"],
                win_rate=metrics["win_rate"],
                sharpe_ratio=0.0,  # Would need price history to calculate
                max_drawdown=0.0,  # Would need to track
            )
            self.state_manager.save_performance_snapshot(snapshot)

            # Wait for next iteration
            await asyncio.sleep(check_interval_minutes * 60)

        # Final summary
        final_capital = await self.get_current_capital()
        final_metrics = self.state_manager.calculate_performance_metrics()

        return {
            "starting_capital": self.starting_capital,
            "ending_capital": final_capital,
            "total_pnl": final_capital - self.starting_capital,
            "total_pnl_pct": ((final_capital - self.starting_capital) / self.starting_capital * 100),
            "iterations": iterations,
            "metrics": final_metrics,
        }


# Main entry functions
async def trade_autonomous(
    starting_capital: float,
    markets: list[str],
    risk_params: Optional[RiskParams] = None,
    duration_hours: int = 24,
    testnet: bool = True,
) -> dict[str, Any]:
    """Start autonomous trading session.

    Args:
        starting_capital: Starting capital in USD
        markets: Markets to trade
        risk_params: Risk management parameters
        duration_hours: Trading duration in hours
        testnet: Use testnet (default: True)

    Returns:
        Trading session summary
    """
    agent = HyperliquidTradingAgent(
        starting_capital=starting_capital,
        risk_params=risk_params,
        testnet=testnet,
    )

    return await agent.run_autonomous_trading(markets=markets, duration_hours=duration_hours)


async def trade_with_strategy(
    starting_capital: float,
    strategy: TradingStrategy,
    risk_params: Optional[RiskParams] = None,
    testnet: bool = True,
) -> dict[str, Any]:
    """Execute a pre-defined trading strategy.

    Args:
        starting_capital: Starting capital in USD
        strategy: Trading strategy to execute
        risk_params: Risk management parameters
        testnet: Use testnet (default: True)

    Returns:
        Execution summary
    """
    agent = HyperliquidTradingAgent(
        starting_capital=starting_capital,
        risk_params=risk_params,
        testnet=testnet,
    )

    results = await agent.execute_strategy_iteration(strategy)

    return results
