"""Trading strategies for Hyperliquid trading agent.

This module implements various trading strategies including trend following,
mean reversion, funding arbitrage, and more.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field


class StrategyType(str, Enum):
    """Available trading strategy types."""

    AUTONOMOUS = "autonomous"  # Agent develops its own strategy
    TREND_FOLLOWING = "trend_following"
    MEAN_REVERSION = "mean_reversion"
    FUNDING_ARBITRAGE = "funding_arbitrage"
    BREAKOUT = "breakout"
    MOMENTUM = "momentum"
    PAIRS_TRADING = "pairs_trading"
    GRID_TRADING = "grid_trading"
    CUSTOM = "custom"


class TimeFrame(str, Enum):
    """Trading timeframes."""

    M1 = "1m"
    M5 = "5m"
    M15 = "15m"
    M30 = "30m"
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"


class SignalStrength(str, Enum):
    """Signal strength levels."""

    VERY_WEAK = "very_weak"
    WEAK = "weak"
    NEUTRAL = "neutral"
    STRONG = "strong"
    VERY_STRONG = "very_strong"


class TradingSignal(BaseModel):
    """Trading signal generated by a strategy."""

    coin: str = Field(..., description="Trading pair")
    action: Literal["buy", "sell", "hold", "close"] = Field(..., description="Recommended action")
    strength: SignalStrength = Field(..., description="Signal strength")
    confidence: float = Field(..., description="Confidence score 0-1")
    entry_price: Optional[float] = Field(None, description="Recommended entry price")
    stop_loss: Optional[float] = Field(None, description="Recommended stop loss price")
    take_profit: Optional[float] = Field(None, description="Recommended take profit price")
    position_size: Optional[float] = Field(None, description="Recommended position size")
    reasoning: str = Field(..., description="Explanation for the signal")
    indicators: dict[str, Any] = Field(default_factory=dict, description="Supporting indicator values")
    timestamp: int = Field(..., description="Signal generation timestamp")


class TradingStrategy(BaseModel):
    """Trading strategy configuration."""

    type: StrategyType = Field(..., description="Strategy type")
    name: str = Field(..., description="Strategy name")
    description: str = Field(..., description="Strategy description")
    markets: list[str] = Field(default_factory=list, description="Markets to trade (e.g., ['BTC', 'ETH'])")
    timeframe: TimeFrame = Field(default=TimeFrame.H1, description="Primary timeframe")

    # Strategy parameters
    parameters: dict[str, Any] = Field(default_factory=dict, description="Strategy-specific parameters")

    # Entry/Exit rules
    entry_rules: Optional[str] = Field(None, description="Entry conditions description")
    exit_rules: Optional[str] = Field(None, description="Exit conditions description")

    # Risk parameters
    risk_per_trade: float = Field(0.02, description="Risk per trade as fraction (e.g., 0.02 = 2%)")
    max_positions: int = Field(3, description="Maximum concurrent positions")
    use_stop_loss: bool = Field(True, description="Use stop losses")
    use_take_profit: bool = Field(True, description="Use take profit orders")

    # Advanced settings
    use_trailing_stop: bool = Field(False, description="Use trailing stop loss")
    trailing_stop_pct: float = Field(0.02, description="Trailing stop percentage")
    partial_close_enabled: bool = Field(False, description="Enable partial position closes")
    pyramiding_enabled: bool = Field(False, description="Allow adding to winning positions")


class StrategyPerformance(BaseModel):
    """Strategy performance metrics."""

    strategy_name: str = Field(..., description="Strategy name")
    total_trades: int = Field(0, description="Total number of trades")
    winning_trades: int = Field(0, description="Number of winning trades")
    losing_trades: int = Field(0, description="Number of losing trades")
    win_rate: float = Field(0.0, description="Win rate percentage")
    total_pnl: float = Field(0.0, description="Total profit/loss")
    average_win: float = Field(0.0, description="Average winning trade")
    average_loss: float = Field(0.0, description="Average losing trade")
    profit_factor: float = Field(0.0, description="Profit factor (gross profit / gross loss)")
    sharpe_ratio: float = Field(0.0, description="Sharpe ratio")
    max_drawdown: float = Field(0.0, description="Maximum drawdown")
    max_drawdown_pct: float = Field(0.0, description="Maximum drawdown percentage")
    average_trade_duration_hours: float = Field(0.0, description="Average trade duration in hours")


# Pre-defined strategy templates
def get_trend_following_strategy(
    markets: list[str],
    timeframe: TimeFrame = TimeFrame.H1,
    risk_per_trade: float = 0.02,
) -> TradingStrategy:
    """Get a trend following strategy configuration.

    This strategy follows strong trends using moving averages and momentum indicators.

    Args:
        markets: List of markets to trade
        timeframe: Trading timeframe
        risk_per_trade: Risk per trade as fraction

    Returns:
        Configured TradingStrategy
    """
    return TradingStrategy(
        type=StrategyType.TREND_FOLLOWING,
        name="Trend Following",
        description="Follow strong trends using MA crossovers and momentum",
        markets=markets,
        timeframe=timeframe,
        parameters={
            "fast_ma_period": 20,
            "slow_ma_period": 50,
            "momentum_period": 14,
            "trend_strength_threshold": 0.7,
            "volume_confirmation": True,
        },
        entry_rules="Enter long when fast MA crosses above slow MA and momentum is positive. Enter short when fast MA crosses below slow MA and momentum is negative.",
        exit_rules="Exit when opposite signal occurs or stop loss/take profit is hit.",
        risk_per_trade=risk_per_trade,
        max_positions=3,
        use_stop_loss=True,
        use_take_profit=True,
        use_trailing_stop=True,
        trailing_stop_pct=0.03,
    )


def get_mean_reversion_strategy(
    markets: list[str],
    timeframe: TimeFrame = TimeFrame.M15,
    risk_per_trade: float = 0.015,
) -> TradingStrategy:
    """Get a mean reversion strategy configuration.

    This strategy trades oversold/overbought conditions expecting price to revert.

    Args:
        markets: List of markets to trade
        timeframe: Trading timeframe
        risk_per_trade: Risk per trade as fraction

    Returns:
        Configured TradingStrategy
    """
    return TradingStrategy(
        type=StrategyType.MEAN_REVERSION,
        name="Mean Reversion",
        description="Trade oversold/overbought conditions with quick profits",
        markets=markets,
        timeframe=timeframe,
        parameters={
            "rsi_period": 14,
            "rsi_oversold": 30,
            "rsi_overbought": 70,
            "bb_period": 20,
            "bb_std": 2,
            "mean_lookback": 50,
        },
        entry_rules="Enter long when RSI < 30 and price touches lower Bollinger Band. Enter short when RSI > 70 and price touches upper Bollinger Band.",
        exit_rules="Exit when price returns to mean or opposite condition occurs.",
        risk_per_trade=risk_per_trade,
        max_positions=4,
        use_stop_loss=True,
        use_take_profit=True,
        use_trailing_stop=False,
    )


def get_funding_arbitrage_strategy(
    markets: list[str],
    timeframe: TimeFrame = TimeFrame.H1,
) -> TradingStrategy:
    """Get a funding rate arbitrage strategy configuration.

    This strategy takes positions based on funding rate opportunities.

    Args:
        markets: List of markets to trade
        timeframe: Trading timeframe

    Returns:
        Configured TradingStrategy
    """
    return TradingStrategy(
        type=StrategyType.FUNDING_ARBITRAGE,
        name="Funding Arbitrage",
        description="Capture funding rate payments by taking contrarian positions",
        markets=markets,
        timeframe=timeframe,
        parameters={
            "funding_threshold": 0.01,  # 1% funding rate threshold
            "min_hold_hours": 8,  # Minimum hours to hold position
            "max_hold_hours": 24,  # Maximum hours to hold position
        },
        entry_rules="Enter short when funding rate is very positive (longs pay shorts). Enter long when funding rate is very negative (shorts pay longs).",
        exit_rules="Exit after collecting funding payments or if price moves significantly against position.",
        risk_per_trade=0.03,
        max_positions=5,
        use_stop_loss=True,
        use_take_profit=False,
    )


def get_breakout_strategy(
    markets: list[str],
    timeframe: TimeFrame = TimeFrame.H4,
    risk_per_trade: float = 0.025,
) -> TradingStrategy:
    """Get a breakout strategy configuration.

    This strategy trades breakouts from consolidation ranges.

    Args:
        markets: List of markets to trade
        timeframe: Trading timeframe
        risk_per_trade: Risk per trade as fraction

    Returns:
        Configured TradingStrategy
    """
    return TradingStrategy(
        type=StrategyType.BREAKOUT,
        name="Breakout Trading",
        description="Trade breakouts from consolidation with volume confirmation",
        markets=markets,
        timeframe=timeframe,
        parameters={
            "lookback_period": 50,
            "breakout_threshold": 0.02,  # 2% move from range
            "volume_multiplier": 1.5,  # Volume should be 1.5x average
            "consolidation_min_periods": 20,
        },
        entry_rules="Enter when price breaks above resistance or below support with high volume.",
        exit_rules="Exit when momentum fades or stop loss is hit.",
        risk_per_trade=risk_per_trade,
        max_positions=2,
        use_stop_loss=True,
        use_take_profit=True,
        use_trailing_stop=True,
        trailing_stop_pct=0.04,
    )


def get_momentum_strategy(
    markets: list[str],
    timeframe: TimeFrame = TimeFrame.M30,
    risk_per_trade: float = 0.02,
) -> TradingStrategy:
    """Get a momentum strategy configuration.

    This strategy follows strong directional moves with momentum indicators.

    Args:
        markets: List of markets to trade
        timeframe: Trading timeframe
        risk_per_trade: Risk per trade as fraction

    Returns:
        Configured TradingStrategy
    """
    return TradingStrategy(
        type=StrategyType.MOMENTUM,
        name="Momentum Trading",
        description="Follow strong directional momentum with quick entries/exits",
        markets=markets,
        timeframe=timeframe,
        parameters={
            "rsi_period": 14,
            "rsi_momentum_threshold": 60,  # Above 60 for long, below 40 for short
            "atr_period": 14,
            "momentum_strength_min": 0.6,
            "volume_confirmation": True,
        },
        entry_rules="Enter when strong momentum is confirmed by multiple indicators and volume.",
        exit_rules="Exit when momentum weakens or reverses.",
        risk_per_trade=risk_per_trade,
        max_positions=3,
        use_stop_loss=True,
        use_take_profit=True,
        use_trailing_stop=True,
        trailing_stop_pct=0.025,
        partial_close_enabled=True,
    )


def get_grid_trading_strategy(
    markets: list[str],
    grid_levels: int = 10,
    grid_spacing_pct: float = 0.01,
) -> TradingStrategy:
    """Get a grid trading strategy configuration.

    This strategy places buy and sell orders at regular intervals (grid).

    Args:
        markets: List of markets to trade
        grid_levels: Number of grid levels
        grid_spacing_pct: Spacing between grid levels as percentage

    Returns:
        Configured TradingStrategy
    """
    return TradingStrategy(
        type=StrategyType.GRID_TRADING,
        name="Grid Trading",
        description="Place orders at regular price intervals to profit from ranging markets",
        markets=markets,
        timeframe=TimeFrame.M15,
        parameters={
            "grid_levels": grid_levels,
            "grid_spacing_pct": grid_spacing_pct,
            "base_order_size": 0.01,
            "range_detection": True,
        },
        entry_rules="Place buy orders below current price and sell orders above at fixed intervals.",
        exit_rules="Each order pair (buy + sell) takes profit automatically.",
        risk_per_trade=0.01,
        max_positions=grid_levels,
        use_stop_loss=False,  # Grid trading typically doesn't use stops
        use_take_profit=True,
    )


# Strategy selection helper
def get_strategy_by_type(
    strategy_type: StrategyType,
    markets: list[str],
    **kwargs,
) -> TradingStrategy:
    """Get a pre-configured strategy by type.

    Args:
        strategy_type: Type of strategy to get
        markets: Markets to trade
        **kwargs: Additional parameters to pass to strategy

    Returns:
        Configured TradingStrategy
    """
    strategy_map = {
        StrategyType.TREND_FOLLOWING: get_trend_following_strategy,
        StrategyType.MEAN_REVERSION: get_mean_reversion_strategy,
        StrategyType.FUNDING_ARBITRAGE: get_funding_arbitrage_strategy,
        StrategyType.BREAKOUT: get_breakout_strategy,
        StrategyType.MOMENTUM: get_momentum_strategy,
        StrategyType.GRID_TRADING: get_grid_trading_strategy,
    }

    if strategy_type not in strategy_map:
        raise ValueError(f"Unknown strategy type: {strategy_type}")

    return strategy_map[strategy_type](markets=markets, **kwargs)
